apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: evenx-prod

resources:
- ../../base
- namespace.yaml

commonLabels:
  environment: prod

images:
- name: praxis-innovations
  newName: praxisinnovations/praxis-innovations
  newTag: latest

patches:
- target:
    kind: Ingress
    name: praxisinnovations-ingress
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: praxisinnovations.ca
    - op: replace
      path: /spec/tls/0/hosts/0
      value: praxisinnovations.ca
    - op: replace
      path: /spec/tls/0/secretName
      value: praxisinnovations-tls-prod
